"""The all-in-one Rhino / Grasshopper file rhino/rav4shelf_rhino.py.

It is generated by tools/bundle_rhino.py from src/ and params/default.json.
These tests check that it is up to date, that it runs without the repo (the
embedded package and spec), and run its main() against mocked Rhino, System
and Grasshopper modules, once as a Rhino script and once as a Grasshopper
Script component.
"""
import importlib.util
import os
import subprocess
import sys
import textwrap

from conftest import REPO

BUNDLE = os.path.join(REPO, "rhino", "rav4shelf_rhino.py")


def _generator():
    spec = importlib.util.spec_from_file_location("bundle_rhino",
                                                  os.path.join(REPO, "tools", "bundle_rhino.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_bundle_is_up_to_date():
    with open(BUNDLE, encoding="utf-8") as f:
        committed = f.read()
    assert committed == _generator().render(), \
        "rhino/rav4shelf_rhino.py is stale: run python tools/bundle_rhino.py"


def _run(code, tmp_path):
    """Run code in a fresh interpreter, away from the repo (-I: no PYTHONPATH,
    no current directory on sys.path)."""
    script = tmp_path / "run.py"
    script.write_text("BUNDLE = %r\n" % BUNDLE + textwrap.dedent(code), encoding="utf-8")
    out = subprocess.run([sys.executable, "-I", str(script)], cwd=str(tmp_path),
                         capture_output=True, text=True, timeout=120)
    assert out.returncode == 0, out.stdout + out.stderr
    return out.stdout


def test_bundle_runs_without_the_repo(tmp_path):
    out = _run("""
        import os, runpy, sys
        g = runpy.run_path(BUNDLE, run_name="not_main")  # loads, does not build
        g["_install"]()
        import rav4shelf
        from rav4shelf import checks, meshing, params
        assert rav4shelf.__file__.startswith("<rav4shelf_rhino.py>"), rav4shelf.__file__
        assert not os.path.isfile(params.DEFAULT_SPEC_PATH)  # spec comes from the bundle
        p = params.load_params({"envelope_offset": 0.5})
        d = params.derive(p)
        assert not checks.has_errors(checks.run_checks(p, d))
        assert meshing.check_closed(meshing.coupon_mesh(p, d)) == []
        assert meshing.check_closed(meshing.envelope_mesh(p, d)) == []
        g["_install"]()  # second run (Rhino keeps modules): same package kept
        assert sys.modules["rav4shelf"] is rav4shelf
        print("W_ref", p.W_ref)
        """, tmp_path)
    assert "W_ref 231.55" in out


MOCKS = """
    import runpy, sys
    from unittest import mock

    rhino, system, grasshopper = mock.MagicMock(), mock.MagicMock(), mock.MagicMock()
    for name, mod in {"Rhino": rhino, "Rhino.Geometry": rhino.Geometry,
                      "Rhino.DocObjects": rhino.DocObjects, "System": system,
                      "System.Collections": system.Collections,
                      "System.Collections.Generic": system.Collections.Generic,
                      "System.Drawing": system.Drawing, "Grasshopper": grasshopper,
                      "Grasshopper.Kernel": grasshopper.Kernel}.items():
        sys.modules[name] = mod
    rg = rhino.Geometry
    doc = rhino.RhinoDoc.ActiveDoc
    doc.ModelUnitSystem = rhino.UnitSystem.Millimeters
    doc.ModelAbsoluteTolerance = 0.001
    doc.Layers.FindByFullPath.return_value = 3
    doc.Objects.FindByLayer.return_value = []

    class Brep(mock.MagicMock):  # real classes, so that bake()'s isinstance works
        pass

    rg.Brep, rg.Curve, rg.Mesh = Brep, type("Curve", (), {}), type("Mesh", (), {})

    def solid():
        b = Brep()
        b.IsSolid = b.IsValid = True
        return b

    loft = mock.MagicMock()
    loft.CapPlanarHoles.return_value = solid()
    Brep.CreateFromLoft = mock.MagicMock(return_value=[loft])
    Brep.CreateBooleanDifference = mock.MagicMock(return_value=[solid()])
    rg.PolyCurve.return_value.Append.return_value = True
    rg.PolyCurve.return_value.IsClosed = True
"""


def test_bundle_main_in_rhino(tmp_path):
    out = _run(MOCKS + """
    runpy.run_path(BUNDLE, run_name="__main__")
    print("baked", sorted({c.args[0] for c in doc.Layers.FindByFullPath.call_args_list}))
    print("breps", doc.Objects.AddBrep.call_count)
    """, tmp_path)
    assert "fit_coupon: built by boolean" in out
    assert "profile_gauge: built by boolean" in out
    for layer in ("fit_coupon", "profile_gauge", "envelope", "cubby", "ports", "phone"):
        assert "RAV4chargerShelf::" + layer in out
    assert "breps 3" in out  # coupon, gauge, envelope (the plug and phone boxes are mocks)


def test_bundle_main_stops_on_wrong_units(tmp_path):
    out = _run(MOCKS + """
    doc.ModelUnitSystem = "Inches"
    runpy.run_path(BUNDLE, run_name="__main__")
    """, tmp_path)
    assert "STOP: document units are Inches" in out and "Nothing built" in out
    assert "built by" not in out


def test_bundle_in_grasshopper(tmp_path):
    out = _run(MOCKS + """
    def source(nick, value):
        src = mock.MagicMock()
        src.NickName = nick
        goo = mock.MagicMock()
        goo.ScriptVariable.return_value = value
        src.VolatileData.AllData.return_value = [goo]
        return src

    s_input = mock.MagicMock()
    s_input.NickName = "S"
    s_input.Sources = [source("side_gap", 0.4), source("Number Slider", 1.0)]
    s_input.SourceCount = 2
    s_input.Access = grasshopper.Kernel.GH_ParamAccess.list
    ghenv = mock.MagicMock()
    ghenv.Component.Params.Input = [s_input]
    g = runpy.run_path(BUNDLE, init_globals={"ghenv": ghenv, "export": False},
                       run_name="ghscript")
    assert g["coupon"] is not None and g["gauge"] is not None and g["envelope"] is not None
    assert len(g["cubby"]) == 6 + 2
    assert not doc.Objects.AddBrep.called  # Grasshopper shows, it does not bake
    print(g["report"])
    """, tmp_path)
    assert "fit_coupon: built by boolean" in out
    assert "params: default.json + grasshopper" in out          # slider value used
    assert "ignored (name is not a parameter): Number Slider" in out
