"""Build rhino/rav4shelf_rhino.py: ONE self-contained file for Rhino 8 and
Grasshopper. It embeds the Rhino-related modules of src/rav4shelf and
params/default.json, so it runs without the repo next to it.

    python tools/bundle_rhino.py

CI fails if the committed file is stale (tests/test_bundle.py). Edit the code
in src/ and regenerate; do not edit the generated file.
"""
import ast
import hashlib
import os

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))
OUT = os.path.join(REPO, "rhino", "rav4shelf_rhino.py")
# load order: a module comes after everything it imports at module level
MODULES = ["__init__", "geom2d", "params", "layout", "checks", "meshing", "fileio", "geometry",
           "export", "gh"]

HEADER = '''#! python3
"""RAV4chargerShelf - all-in-one script for Rhino 8 and Grasshopper.

This is a Python 3 script. Rhino's old IronPython 2 engine cannot run it: do
not use EditPythonScript, or the "Python Script" / "IronPython 2 Script"
components in Grasshopper.

RHINO 8
  1. Set the document units to millimetres (command: Units).
  2. Type ScriptEditor and press Enter. Open this file there (File > Open), or
     make a new script, choose Python 3, and paste this whole file into it.
  3. Press Run (the green triangle, or F5).
  (RunPythonScript with the saved file also works: its first line,
  "#! python3", selects Python 3.)
  The parts appear on layers RAV4chargerShelf::<part> and the report in the
  output pane. Running it again replaces them. The layer "envelope" (the cubby
  as a solid) starts switched off; turn it on in the Layers panel, ideally in
  the X-Ray display mode. Change the SETTINGS below and run again.

GRASSHOPPER
  Paste this file into a "Python 3 Script" component; it then shows the parts
  live and reads sliders. Step by step: docs/grasshopper_onboarding.md.

Generated by tools/bundle_rhino.py from the RAV4chargerShelf repository
(version %(version)s). Change only the SETTINGS; to update, replace the whole file.
"""
import sys

if sys.version_info[0] < 3:  # stop before anything Python 2 cannot run
    raise RuntimeError(
        "This script needs Python 3, but it is running in IronPython 2 (the old "
        "EditPythonScript editor, or the 'Python Script' component in Grasshopper). "
        "In Rhino 8 use the ScriptEditor command and choose Python 3; in Grasshopper "
        "use the 'Python 3 Script' component.")

# ============================== SETTINGS ===================================
# Your values; everything not listed uses the defaults (docs/parameters.md).
# Copy lines from params/measured.json, e.g. "envelope_offset": 0.8,
MY_VALUES = {
    # "envelope_offset": 0.0,   # gap per side you saw on the fit coupon
    # "side_gap": 0.0,
    # "shelf_height": 58.0,
    # "H_ports_top": 40.0,
}

# What to build: "fit_coupon", "profile_gauge" (the two test prints) and
# "envelope" (the cubby as a solid, to design against).
BUILD = ["fit_coupon", "profile_gauge", "envelope"]

# Show the cubby wireframe, the plug cluster, the phone and the free zone
# around the roof LED as reference.
SHOW_CUBBY = True

# Folder for STL + 3MF + STEP files of the test prints, e.g.
# r"C:\\Users\\you\\Desktop\\rav4shelf". Empty = do not export. In Grasshopper
# the files are written when the "export" input is true (empty = next to the .gh).
EXPORT_FOLDER = r""
# ===========================================================================
'''

LOADER = r'''

# ---------------------------------------------------------------------------
# Everything below is generated. It loads the embedded sources as the package
# "rav4shelf", then builds the parts. Keep it plain Python 2 syntax too, so
# IronPython reaches the version check at the top instead of a syntax error.
# ---------------------------------------------------------------------------
import os
import types


def _install():
    """Load the embedded package into sys.modules, in dependency order. Rhino
    keeps modules between runs, so another version (or a repo checkout) is
    dropped first."""
    pkg = sys.modules.get("rav4shelf")
    if pkg is not None and getattr(pkg, "_BUNDLE_VERSION", None) == BUNDLE_VERSION:
        return
    _drop()
    # an import hook left behind by older versions of this file
    sys.meta_path[:] = [f for f in sys.meta_path if type(f).__name__ != "_BundleImporter"]
    try:
        pkg = _load("rav4shelf", "__init__")
        for key in _ORDER[1:]:
            mod = _load("rav4shelf." + key, key)
            setattr(pkg, key, mod)
            if key == "params":
                mod.EMBEDDED_SPEC = _SPEC_JSON
    except BaseException:
        _drop()  # no half-loaded package for the next run
        raise
    pkg._BUNDLE_VERSION = BUNDLE_VERSION


def _drop():
    for name in [n for n in sys.modules if n == "rav4shelf" or n.startswith("rav4shelf.")]:
        del sys.modules[name]


def _load(name, key):
    mod = types.ModuleType(name)
    mod.__file__ = "<rav4shelf_rhino.py>/rav4shelf/%s.py" % key
    mod.__package__ = "rav4shelf"
    if key == "__init__":
        mod.__path__ = []  # a package: "from . import x" finds x in sys.modules
    sys.modules[name] = mod
    code = compile(_SOURCES[key], mod.__file__, "exec", dont_inherit=True)
    exec(code, mod.__dict__)
    return mod


def _export_folder(component):
    if EXPORT_FOLDER:
        return EXPORT_FOLDER
    if component is not None:
        doc = component.OnPingDocument()
        if doc is not None and doc.FilePath:
            return os.path.join(os.path.dirname(doc.FilePath), "rav4shelf_out")
    return ""


def main():
    try:
        import Rhino
    except ImportError:
        print("Run this inside Rhino 8 (ScriptEditor) or a Grasshopper Python 3 Script component.")
        return
    _install()
    from rav4shelf import checks, export, geometry, gh, params

    g = globals()
    component = g["ghenv"].Component if "ghenv" in g else None
    p = params.load_params(MY_VALUES)
    notes = []
    if component is not None:
        values, ignored, notes = gh.read_named_inputs(component, p.spec)
        if values:
            p = p.with_overrides(values, "grasshopper")
        if ignored:
            notes.append("ignored (name is not a parameter): " + ", ".join(ignored))
    d = params.derive(p)
    findings = checks.run_checks(p, d)
    report = [checks.format_report(p, d, findings)] + notes
    doc = Rhino.RhinoDoc.ActiveDoc
    units = export.check_units(doc)
    if units:
        report.append(("WARNING: " if component else "STOP: ") + units)
    if checks.has_errors(findings) or (units and component is None):
        report.append("Nothing built: fix the problems above.")
        _finish(component, report, {}, None, {})
        return
    tol = min(doc.ModelAbsoluteTolerance, geometry.DEFAULT_TOL)

    parts = {}  # name -> (solid to export, solid to show in the car frame)
    if "fit_coupon" in BUILD:
        coupon, method = geometry.build_fit_coupon(p, d, tol)
        parts["fit_coupon"] = (coupon, coupon)
        report.append("fit_coupon: built by %s" % method)
    if "profile_gauge" in BUILD:
        flat, standing, method = geometry.build_profile_gauge(p, d, tol)
        parts["profile_gauge"] = (flat, standing)
        report.append("profile_gauge: built by %s" % method)
    for name, (solid, _) in parts.items():
        report += ["  PROBLEM: " + m for m in geometry.check_solid(solid, name)]
    envelope = geometry.build_envelope(p, d, tol) if "envelope" in BUILD else None
    context = geometry.build_context(p, d) if SHOW_CUBBY else {}

    folder = _export_folder(component)
    if folder and (component is None or g.get("export")):
        for name, (solid, _) in parts.items():
            paths, msgs = export.export_part(name, [solid], folder, ("step", "3mf", "stl"), tol,
                                             doc if component is None else None)
            report += ["  wrote " + x for x in paths] + ["  PROBLEM: " + m for m in msgs]
    elif component is not None and g.get("export"):
        report.append("export: save the .gh file first, or set EXPORT_FOLDER")

    if component is not None and g.get("sliders"):
        groups = [x.strip() for x in (g.get("groups") or "").split(",") if x.strip()]
        report.append("creating %d sliders..." % gh.schedule_slider_bank(component, p, groups))
    if p.placeholders:
        report.append("%d values are not confirmed for your car yet (see the report above)."
                      % len(p.placeholders))
    _finish(component, report, parts, envelope, context)


def _finish(component, report, parts, envelope, context):
    text = "\n".join(report)
    if component is None:  # Rhino: bake to layers
        import Rhino
        from rav4shelf import export
        doc = Rhino.RhinoDoc.ActiveDoc
        for name, geo in context.items():
            export.bake(doc, name, geo)
        for name, (_, shown) in parts.items():
            export.bake(doc, name, [shown])
        if envelope is not None:
            export.bake(doc, "envelope", [envelope])
        doc.Views.Redraw()
        print(text)
        return
    g = globals()  # Grasshopper: fill the outputs that exist on the component
    g["coupon"] = parts.get("fit_coupon", (None, None))[1]
    g["gauge"] = parts.get("profile_gauge", (None, None))[1]
    g["envelope"] = envelope
    g["cubby"] = sum((context.get(k, []) for k in ("cubby", "led_keepout", "ports", "phone")), [])
    g["report"] = text


if __name__ == "__main__" or "ghenv" in globals():
    main()
'''


def _check_order(sources) -> None:
    """MODULES is the load order: every module-level relative import must
    name a module listed before it."""
    for i, name in enumerate(MODULES):
        for node in ast.parse(sources[name]).body:
            if isinstance(node, ast.ImportFrom) and node.level == 1:
                deps = [node.module] if node.module else [a.name for a in node.names]
                late = [x for x in deps if x not in MODULES[:i]]
                if late:
                    raise SystemExit("%s imports %s: list it earlier in MODULES" % (name, late))


def render() -> str:
    sources = {}
    for name in MODULES:
        with open(os.path.join(REPO, "src", "rav4shelf", name + ".py"), encoding="utf-8") as f:
            sources[name] = f.read()
    with open(os.path.join(REPO, "params", "default.json"), encoding="utf-8") as f:
        spec_json = f.read()
    digest = hashlib.sha1("".join([sources[n] for n in MODULES] + [spec_json, HEADER, LOADER])
                          .encode("utf-8")).hexdigest()[:10]
    _check_order(sources)
    out = [HEADER % {"version": digest},
           "\nBUNDLE_VERSION = %r\n\n_ORDER = %r\n\n_SOURCES = {\n" % (digest, MODULES)]
    for name in MODULES + ["<spec>"]:
        text = spec_json if name == "<spec>" else sources[name]
        if "'''" in text or text.endswith("\\"):
            raise SystemExit("%s cannot be embedded in a r''' string" % name)
    for name in MODULES:
        out.append("    %r: r'''%s''',\n" % (name, sources[name]))
    out.append("}\n\n_SPEC_JSON = r'''%s'''\n" % spec_json)
    out.append(LOADER)
    return "".join(out)


if __name__ == "__main__":
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(render())
    print("wrote " + os.path.relpath(OUT, REPO))
